## Übersicht: Schritte zur Verwendung eines *IRTlib Player* zur *Datenerhebung*

Nachdem eine *Studie* mit dem *IRTlib Editor* angelegt und konfiguriert wurde, muss eine finalisierte *Version* dieser Konfiguration erstellt werden. Versionen *versiegeln* und vervollständigen alle Konfigurationen und haben eine eindeutige Versionsnummer (bezeichnet als *Revision*). Die Verwendung von *Revisionen* macht die Durchführung von Datensammlungen mit dem *IRTlib Editor* und *IRTlib Player* reproduzierbar, da die Revisionsnummer einer Konfiguration auch in den Datensätzen gespeichert wird.

* **Konfigurationen Prüfen**: Vor der Fertigstellung und dem *Versiegeln* einer Version ist es ratsam, alle Einstellungen noch einmal zu überprüfen. Der *IRTlib-Editor* stellt dafür eine zusätzliche Funktion der *Validierung* zur Verfügung.  

* **Versiegelte Version Erstellen**: Wenn keine weiteren Änderungen erforderlich sind, kann die Version *versiegelt* werden. Dies geschieht durch das Auswählen der noch nicht gespeicherten Änderungen und einen Klick auf das Schloss-Symbol im *IRTlib Editor* in der Ansicht *Veröffentlichen*, in welcher die *Studienrevisionen* angezeigt werden. . 

* **Version Exportieren**: Versionen von Studien, die im *IRTlib-Editor* verfügbar sind, können exportiert werden. Der Export der Konfiguration ist notwendig, bevor diese mit dem *IRTlib-Player* verwendet werden können. Beim Exportieren wird die vollständige Studienkonfiguration inklusive der importierten *CBA ItemBuilder*-Inhalte als ZIP-Archiv heruntergeladen. 

* **Studie in *IRTlib Player* Importieren**: Exportierte Versionen von Studien aus dem *IRTlib-Editor* können zur Verwendung in einen *IRTlib-Player* importiert werden. Für einzelne *Studien* gibt es einen automatischen Modus, wenn mehrere *Studien* in einem *IRTlib Player* simultan verwendet werden sollen, kann diese manuell erfolgen.  

* **Testen der Studie**: Bevor mit der eigentlichen Datenerfassung begonnen werden kann, sollte jede Konfiguration zunächst mit synthetischen Testfällen (d.h. systematisch) getestet werden. 

Falls in einer exportierten Studie noch Probleme festgestellt werden, ist es möglich, zur Vorbereitung (siehe [Vorbereitung von Studien](preparation-studies.qmd) und [Vorbereitung von Erhebungsteilen](preparation-parts.qmd)) zurückzukehren, die Studiendefinition und die Konfiguration der Testteile zu ändern, eine weitere versiegelte Version zu erstellen und mit der geänderten Konfiguration fortzufahren.
