Die *IRTlib*-Software wird für die Offline-Nutzung (z.Zt. für Windows-Betriebssysteme) und für die Online-Nutzung (in Form von *Docker-Containern*) bereitgestellt.

## Offline (Windows)

Die *IRTlib*-Software (*IRTlib Editor* und *IRTlib Player*) für die Offline-Nutzung kann aus dem Abschnitt [Releases] des Repository <https://github.com/DIPFtba/IRTlibDeploymentSoftware> bezogen und heruntergeladen werden.

Im Abschnitt [Releases](https://github.com/DIPFtba/IRTlibDeploymentSoftware/releases) stehen zwei ZIP-Archive zum Download bereit.

* **`TestApp.Editor.Desktop.exe`**: Ist in `TestApp.Editor.Desktop.zip`  und muss gestartet werden, umd den  *IRTlib Editor* zu verwenden. 

* **`TestApp.Player.Desktop.exe`**: Ist in `TestApp.Player.Desktop.zip` enthalten und muss gestartet werden, umd den  *IRTlib Player* zu verwenden. 

::: {.callout-note collapse="true" title="Hinweis: Versionen aus der aktuellen Entwicklung als *Preview*."}
Beachten Sie, dass der aktuellste Build im Abschnitt [Preview](https://github.com/DIPFtba/IRTlibDeploymentSoftware/releases/tag/preview-231025) des *Release*-Abschnitts des [repository](https://github.com/DIPFtba/IRTlibDeploymentSoftware/releases) zu finden ist. Preview-Versionen sind die aktuellsten Version der Software, nach der letzten veröffentlichten Version der *IRTlib Software*. Um reproduzierbare Ergebnisse zu erhalten, sollten immer veröffentlichte Versionen verwendet werden. 
:::

::: {.callout-warning collapse="false" title="Hinweis: Warnmeldung beim Programmstart"}
Die automatisch erstellten Vorschauversionen des *IRTlib Editors* und *IRTlib Players* sind nicht signiert. Eine Warnmeldung des Betriebssystems muss akzeptiert werden, bevor die Programme ausgeführt werden können. Je nach Konfiguration des Betriebssystems können die ausführbaren Dateien der *IRTlib Software* auch als unbekannt eingestuft und vor ihrer Verwendung zusätzlich gewarnt werden. 
:::

### Studienvorbereitung mit Offline Editor

Der *IRTlib Editor* für die Offline-Nutzung wird als ZIP-Archiv (z.B. `TestApp.Editor.Desktop.zip`) bereitgestellt, das entpackt werden muss. Nach dem Entpacken des Editors kann die Anwendung `TestApp.Editor.Desktop.exe` auf einem Windows-Gerät gestartet werden.

In den Abschnitten [Vorbereitung > Übersicht](preparation-overview.qmd), [Vorbereitung > Studien](preparation-studies.qmd) und [Vorbereitung > Erhebungsteile](preparation-parts.qmd) ist dokumentiert, wie man mit Hilfe von *CBA ItemBuilder*-Items Datenerhebungen vorbereitet und konfiguriert.

### Studiendurchführung mit Offline Player 

Der *IRTlib Player* ist auch als Windows-Anwendung für die Offline-Nutzung verfügbar und wird als ZIP-Archiv (z.B. `TestApp.Player.Desktop.zip`) bereitgestellt. Nach dem Entpacken des *IRTlib Player* ist eine veröffentlichte Studienkonfiguration erforderlich, die zur Datenerhebung verwendet werden soll.  

Nach dem Hinzufügen der als Studienkonfiguration bereitgestellten Inhalte einer veröffentlichten Studie kann die ausführbare Datei `TestApp.Player.Desktop.exe` gestartet werden (entweder mit oder ohne Startparameter). 

* **Kiosk Mode**: Der *IRTlib Player* kann über die ausführbare Datei `TestApp.Player.Desktop.exe` auf dem Computer, auf dem er lokal ausgeführt wird, direkt zur Datenerhebung verwendet werden. Die *Studie* kann dazu so konfiguriert werden, dass es in einem *Kiosk Mode* auf einem Bildschirm angezeigt wird und nur über den *Task Manager* oder das *Testleitermenü* beendet werden kann (siehe *Vollbildmodus* im Abschnitt [Konfiguration zur Anzeige](preparation-studies.html#konfiguration-zur-anzeige)).

* **Lokaler Server**: Der *IRTlib Player* kann aber auch als lokaler Server ausgeführt werden. Nach dem Start des Programms `TestApp.Player.Server.exe` kann eine konfigurierte *Studie* auch über *Webbrowser* oder andere Browser mit *Kiosk Mode* ausgeliefert werden (z.B. den [Safe Exam Browser](https://safeexambrowser.org/)). Mit dieser Konfiguration lassen sich Datenerhebungen bspw. in Schulen ohne Internetverbindung aber mit einem als *Bring-in*-Server fungierenden Notebook durchführen.

In den Abschnitten [Datenerhebung > Übersicht](data-collection-overview.qmd), [Datenerhebung > Veröffentlichen & Export](data-collection-publish-and-export.qmd) und [Datenerhebung > Integration & Auslieferung](data-collection-player-integration.qmd) ist dokumentiert, wie man mit Hilfe des *IRTlib Players* in den unterschiedlichen Konstellationen Datenerhebungen durchführen kann. 

## Online (Docker)

Die *IRTlib*-Software (*IRTlib Editor* und *IRTlib Player*) für die Online-Nutzung kann als *Docker*-Container bezogen werden. Ein Beispiel ist unter <https://github.com/DIPFtba/IRTlibDeploymentSoftware> zu finden. 


Wenn in der Datei `docker-compose.yml` nichts geändert wird, ist der Editor über Port *8002* und die Player-Software über Port *8001* erreichbar.

In dem Abschnitt [Datenerhebung > Integration & Auslieferung](data-collection-player-integration.qmd) finden sich weitere Informationen zur Verwendung der *Docker*-Container. 
