## IRTLib Software

Die *IRTlib Software* ist freie *Forschungssoftware* im Sinne von *Open Science*. Sie kann für nicht-kommerzielle Anwendungen verwendet werden. 

Vorgeschlagene Zitierung:

> Kroehne, U. (2023). IRTlib Documentation: Software for the administration and delivery of computer-based assessments [IRTlib Dokumentation: Software für die Verwaltung und Auslieferung computergestützter Assessments]. DIPF, Frankfurt am Main, Germany. https://doi.org/10.5281/zenodo.10441352

::: callout-note
Übersetzung: Wenn Sie uns bei der Übersetzung dieser Software helfen wollen, finden Sie [hier](translation.qmd) weitere Informationen.
:::

### Download

* Aktuelle Versionen der IRTlib Software (Windows und Docker): [GitHub](https://github.com/DIPFtba/IRTlibDeploymentSoftware)
* Dokumentation: [GitHub](https://github.com/kroehne/IRTLibDocumentation)

## CBA ItemBuilder

Die *IRTlib Software* erlaubt die Administration von Assessmentinhalten, die mit dem CBA ItemBuilder erstellt wurden. 

### Download

* Aktuelle Versionen des CBA ItemBuilder (Windows): [https://www.itembuilder.de/software](https://www.itembuilder.de/software)

### Source Code 

Source Code und Material zum CBA ItemBuilder sind aufgeteilt auf mehrere Repositorien: 

* CBA ItemBuilder (Desktop Anwendung): [GitHub](https://github.com/DIPFtba/CBAItemBuilderDesktopEditor) (In Vorbereitung / noch privat)
* Laufzeitumgebung / Runtime: [GitHub](https://github.com/DIPFtba/CBAItemBuilderRuntime) (In Vorbereitung / noch privat)
* Ausführungsumgebung / Execution Environment für Entwickler: [GitHub](https://github.com/DIPFtba/CBAItemBuilderExecutionEnvironment) (In Vorbereitung / noch privat)
* Technische Dokumentation: [GitHub](https://github.com/DIPFtba/CBAItemBuilderDocumentation) (In Vorbereitung / noch privat)
* Technische Beispielitems: [GitHub](https://github.com/DIPFtba/CBAItemBuilderExampleItems)(In Vorbereitung / noch privat)

### Dokumentation 

Online-Dokumentation

* HTML (interaktiv): [https://cba.itembuilder.de](https://cba.itembuilder.de)  
* PDF (statisch): [Open-Assessments-with-CBA-ItemBuilder.pdf](https://cba.itembuilder.de/Open-Assessments-with-CBA-ItemBuilder.pdf)
* Quellen [GitHub](https://github.com/kroehne/CBAItemBuilderBook) (In Vorbereitung / noch privat)

Vorgeschlagene Zitierung:

> Kroehne, U. (2023). Open Computer-based Assessment with the CBA ItemBuilder.
> DIPF, Frankfurt am Main, Germany. https://doi.org/10.5281/zenodo.10359757 
