project:
  type: book
  output-dir: ./_book/de
  
book:
  title: "IRTlib Dokumentation: Software für die Verwaltung und Auslieferung computergestützter Assessments"
  author: "Ulf Kroehne"
  date: last-modified
  date-format: "[Letzte Änderung: ] D. MMMM YYYY [\\newline  \\newline  \\newline  Vorgeschlagene Zitierung:]"
  chapters:
    - index.qmd 
    - download.qmd
    - part: "Vorbereitung / Preparation" 
      chapters:
      - preparation-overview.qmd
      - preparation-studies.qmd
      - preparation-parts.qmd
    - part: "Datenerhebung / Data Collection" 
      chapters:
      - data-collection-overview.qmd
      - data-collection-publish-and-export.qmd
      - data-collection-player-integration.qmd
      - data-collection-post-processing.qmd
    - part: "Allgemein / General" 
      chapters:
      - settings.qmd
      - github.qmd      
      - about.qmd
       
format: 
  html:
    theme: cosmo
  pdf: 
    include-in-header: 
       - "tex/general.tex"
    include-before-body:
       - "tex/pagestyle.tex"
    toc: true
    number-depth: 4

lang: de       

execute:
  freeze: false 