project:
  type: book
  output-dir: ./_book/en
  
book:
  title: "IRTlib Documentation"
  subtitle: "Software for the administration of computer-based assessments"
  author: "Ulf Kroehne"
  date: last-modified
  date-format: "[Laste Change: ] Do MMMM, YYYY"   
  chapters:
    - index.qmd 
    - download.qmd
    - part: "Vorbereitung / Preparation" 
      chapters:
      - preparation-overview.qmd
      - preparation-studies.qmd
      - preparation-parts.qmd
    - part: "Datenerhebung / Data Collection" 
      chapters:
      - data-collection-overview.qmd
      - data-collection-publish-and-export.qmd
      - data-collection-player-integration.qmd
      - data-collection-post-processing.qmd      
    - part: "Allgemein / General" 
      chapters:
      - settings.qmd
      - github.qmd      
      - about.qmd
      
format:
  pdf:
    documentclass: scrreprt
    header-includes: |
      \titlehead{\includegraphics[width=6in]{img/irtlib-cover.png}}

lang: en

execute:
  freeze: false 