project:
  type: website
  output-dir: ./_site
  
website:
  title: "IRTlib"
  page-footer: 
    left: "Copyright 2023-2024, Ulf Kroehne" 
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

profile:
  default: language

