project:
  type: website
  output-dir: ./_site
  
website:
  title: "IRTlib"
  page-footer: 
    right: "2023-2024, Ulf Kroehne" 
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true 
    link-external-icon: true
    link-external-newwindow: true
    
profile:
  default: language

