project:
  type: website
  output-dir: ./_site/de
  
website:
  title: "Home | IRTlib"
  reader-mode: true  
  navbar:
    left: 
      - href: download.qmd
        text: Download
      - text: Vorbereitung
        menu:
          - text: Übersicht
            href: preparation-overview.qmd
          - text: Studien
            href: preparation-studies.qmd
          - text: Erhebungsteile
            href: preparation-parts.qmd  
      - text: Datenerhebung
        menu:
          - text: Übersicht
            href: data-collection-overview.qmd
          - text: Veröffentlichen & Export
            href: data-collection-publish-and-export.qmd
          - text: Integration & Auslieferung
            href: data-collection-player-integration.qmd
          - text: Datenaufbereitung
            href: data-collection-post-processing.qmd
      - href: settings.qmd
        text: Einstellungen
      - href: about.qmd
        text: Über
    right:
      - icon: github
        menu:
          - text: IRTLib Releases
            url:  https://github.com/DIPFtba/IRTlibDeploymentSoftware
          - text: IRTLib Dokumentation
            url:  https://github.com/kroehne/IRTLibDocumentation  
          - text: (mehr)
            url:  github.qmd       
      - href: ../en/index.html
        text: (English Version)
  page-footer: 
    right: "2023-2024, Ulf Kroehne" 
    left: 
      - href: https://tba.dipf.de/de
        text: Zentrum für technologiebasiertes Assessment (TBA-Zentrum)<br/>DIPF | Leibniz-Institut für Bildungsforschung und Bildungsinformation 
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    
lang: de
 
execute:
  freeze: auto 