project:
  type: book
  output-dir: ./_book/en
  
book:
  title: "IRTlib Documentation"
  subtitle: "Software for the administration of computer-based assessments"
  author: "Ulf Kroehne"
  date: last-modified
  date-format: "[Laste Change: ] Do MMMM, YYYY"  
  cover-image: img/irtlib-cover.png  
  chapters:
    - index.qmd 
    - download.qmd
    - preparation-overview.qmd
    - preparation-studies.qmd
    - preparation-parts.qmd
    
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    header-includes: |
      \titlehead{\includegraphics[width=6in]{img/irtlib-cover.png}}

lang: en