project:
  type: book
  output-dir: ./_book/de
  
book:
  title: "IRTlib Dokumentation"
  subtitle: "Software zur Administration von computerbasierten Assessments"
  author: "Ulf Kroehne"
  date: last-modified
  date-format: "[Letzte Änderung: ] D. MMMM, YYYY"
  cover-image: img/irtlib-cover.png  
  chapters:
    - index.qmd 
    - download.qmd
    - preparation-overview.qmd
    - preparation-studies.qmd
    - preparation-parts.qmd

format:
  pdf:
    documentclass: scrreprt
    keep-tex: true
    header-includes: |
      \titlehead{\includegraphics[width=6in]{img/irtlib-cover.png}}

lang: de       