---
format:
  html:
    embed-resources: true
    minimal: true 
    toc: false
---

### Grundkonfiguration für Erhebungsteile 

#### Bezeichnung und Beschreibung

* **Bezeichnung**: Die interne Bezeichnung des Erhebungsteils, welche im *IRTlib Editor* zur Bearbeitung und zur Definition des Ablaufs angezeigt wird. Bezeichnungen dürfen keine Sonderzeichen, Leerzeichen und Umlaute enthalten und nicht mit einer Ziffer beginnen.

* **Beschreibung**: Optionale zusätzliche Beschreibung eines Erhebungsteils.

#### Routing innerhalb von Erhebungsteilen 

* **Routing aktivieren**: Die konfigurierten Assessmentinhalte im Abschnitt *Items* können als lineare Sequenz, d.h. in der konfigurierten Reihenfolge administriert werden. Soll eine davon abweichende Reihenfolge verwendet werden, kann hier die Option *Routing aktivieren* gewählt werden. Die Reihenfolge kann dann im Abschnitt *Routing* als visuelles Programm spezifziert werden.  

#### Weitere Einstellungen

* **Snapshot verwenden**: Damit CBA ItemBuilder *Tasks* mehrfach besucht werden können, wird deren Inhalt beim Verlassen des Items in sogenannten *Snapshots* gespeichert. *Snapshots* können auch dazu verwendet werden, um die Inhalte eines  CBA ItemBuilder *Tasks* zu einem späteren Zeitpunkt erneut darzustellen. Diese Option sollte nur dann deaktiviert werden, wenn es einen gewichtigen Grund gibt und die Konsequenzen (d.h. die dann nicht gespeicherten *Snapshot*-Daten) sorgfältig bedacht wurden. 

