---
title: "IRTlib Editor: Settings"
format:
  html:
    embed-resources: true
    minimal: true 
    toc: false    
---

## Settings

In this area, settings can be made that affect work with the Editor and all studies.

### Runtime management

To configure studies that use CBA ItemBuilder content with the IRTLib Editor, the appropriate runtime environment (*Runtime*) is required for each version. Current tested versions of the CBA ItemBuilder runtime are already stored in the Editor, but runtimes for other versions of the CBA ItemBuilder or updated or corrected runtimes can also be imported into the Editor in this area.

Runtimes that are available in the Editor are automatically integrated as part of the study configuration when studies are published and are thus available to the *IRTLib Player*.

### General settings

Change the language for the editor in this section. The setting selected here has no influence on the language of the assessment content in the configured studies.

## About the program

Under the **Version info** button, you will find a summary of the latest changes and information on the current program version.
