---
format:
  html:
    embed-resources: true
---

# Translation

## Help Requested

::: callout-note
The software has been designed so that it can also be translated into other languages. If you would like to support us in this, please [contact](about.qmd) us.
:::

## Current Translations

* This editor can be used to created localized resx-files for the application: [ResXResourceManager](https://github.com/dotnet/ResXResourceManager)

  - The source file can be found here: (TODO)

* Help (included in the application) is generated using [quarto](https://quarto.org/) from markdown files in this  [folder](https://github.com/kroehne/IRTLibDocumentation/tree/main/help).

  - [Help.de-DE.resx](../Help.de-DE.resx) 
  - [Help.en-US.resx](../Help.en-US.resx)


## Terminology and Standardizing the Notation


| Markdown (DEU)| en-US | de-DEU | ...| 
| --- | ---- | --- | --- | 
|`*IRTlib Player*` | *IRTlib Player* | *IRTlib Player* | |
|`*IRTlib Editor*` | *IRTlib Editor* | *IRTlib Editor* | |
|`*IRTlib Software*` | *IRTlib Software* | *IRTlib Software* | |
|`Offline-*IRTlib Player*` | Offline-*IRTlib Player*| Offline-*IRTlib Player* | |
|`Online-*IRTlib Player*` | Online-*IRTlib Player*| Online-*IRTlib Player* | |
|`*Studie*` | *Study* | *Studie* | |
|`*Erhebungsteil*` | *Study Part    * | *Erhebungsteil* | |
|`*Einstellungen*` | *Settings* | *Einstellungen* | |
|`*Testleitermenü*` | *Session Menu* | *Testleitermenü* | |
|`*Bearbeitungszeit*` | *Completion time* | *Bearbeitungszeit* | |
|`*Bearbeitungszeit begrenzen*` | *Restrict time allowed* | *Bearbeitungszeit begrenzen* | |
|`*Studienversion*` | *Study version* | *Studienversion* | |
|`*Revision*` | *Revision* | *Revision* | |
|`*Vorspann-Item(s)*` | *Prolog Item(s)* | *Vorspann-Item(s)* | |
|`*Nachspann-Items(s)*` | *Epilog Item(s)* | *Nachspann-Items(s)* | |
|`*Testleiter*` | *Test Administrator* | *Testleiter* | |
|`*CBA ItemBuilder*-Items` | *CBA ItemBuilder*-Items | *CBA ItemBuilder*-Items | |
|`*Docker*-Container` | *Docker*-Container | *Docker*-Container | |



 