---
title: "IRTlib Editor: Einstellungen zur Studie"
format:
  html:
    embed-resources: true
    minimal: true 
    toc: false
---

## Einstellungen zur Studie

-   **Bezeichnung**: Wie soll die *Studie* benannt werden? Achten Sie darauf, dass für die Bezeichnung nur Buchstaben (Groß- und Kleinschreibung), Ziffer und ein `_` erlaubt sind.

-   **Beschreibung**: Um eine ausführliche Beschreibung der *Studie* hinterlegen zu können, ist dieses optionle Feld vorgesehen. Hier können auch Sonderzeichen und Umlaute usw. eingegeben werden.

-   **Routing für Erhebungsteile aktivieren**: *Studien* bestehen aus einem oder mehreren *Erhebungsteilen*. Die *Erhebungsteile* werden per Default als lineare Abfolge administriert. Wenn die Option *Routing für Erhebungsteile aktivieren* ausgewählt ist, kann die Reihenfolge der *Erhebungsteile* mit einem Blockly-basierten Routing definiert werden. Dadurch sind dynamische Abfolgen von *Erhebungsteilen* möglich, wobei auch Aufrufparameter der Studie bspw. für die Zuordnung von unterschiedlichen Reihenfolgen genutzt werden können. 

-   **Bildschirmgröße überprüfen**: (Beschreibung folgt)
