on:
  workflow_dispatch:
  push:
    branches: main

name: Publish Website and Build resX file

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: build application
        run: make all
         
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          dotnet-quality: 'preview'  

      - name: Show Structure
        run: |      
           echo `ls $GITHUB_WORKSPACE/`         
           echo `ls $GITHUB_WORKSPACE/tools/` 


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          
   