on:
  workflow_dispatch:
  push:
    branches: main

name: Publish Website and Build resX file

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Get R version
        id: get-r-version
        run: echo "version=$(Rscript -e 'cat(as.character(getRversion()))')" >> $GITHUB_OUTPUT
        shell: bash  
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ steps.get-r-version.outputs.version }}-3-
      - name: Install RMarkdown
        run: |
          install.packages("rmarkdown")
        shell: Rscript {0}

      - name: Install knitr 1.42 to avoid bug in 1.43
        run: |
          devtools::install_version("knitr", version = "1.42")
        shell: Rscript {0}
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          tinytex: true 

      - name: build application
        run: make all
         
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Prepare Temp Folder
        run: |
           mkdir $GITHUB_WORKSPACE/_tmp/    

      - name: Show Structure
        run: |      
           echo `ls $GITHUB_WORKSPACE/`         
           echo `ls $GITHUB_WORKSPACE/vs/` 

      - name: Build Tool 
        run: dotnet build vs/html2resx.sln

      - name: Publish Tool 
        run: dotnet publish vs/html2resx/html2resx.csproj -r ubuntu.16.10-x64 -o "$GITHUB_WORKSPACE/_tmp"

      - name: Run Tool 
        run: |      
           echo `ls $GITHUB_WORKSPACE/`            
           $GITHUB_WORKSPACE/_tmp/html2resx $GITHUB_WORKSPACE/_site/ $GITHUB_WORKSPACE/_site/ ${GITHUB_REF##*/} $(git rev-parse --short "$GITHUB_SHA")
           rm -r $GITHUB_WORKSPACE/_tmp/ 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          
   